### PR TITLE
Trending donzo

### PR DESCRIPTION
**Pull request by Chuck-Gibson**
trending in a stable state, currently loads trending as well as Pushing a clicked post to the main feed with option to add background images to the posts ( requires checking if the post has an image or not first)

### CODE REVIEW

**Comment by hn275** [comment]
Functions great. One small issue with **css** however.

trending_issues

Is there a way we could add some extra padding in for those cards? (or maybe further truncating the text/title)

**Comment by Chuck-Gibson** [comment]
100% actually has the same idea and may have fixed on a separate branch. Will get the patch up by days end

**Comment by Chuck-Gibson** [comment]
> Functions great. One small issue with **css** however.
> 
> trending_issues
> 
> Is there a way we could add some extra padding in for those cards? (or maybe further truncating the text/title)

Modified the Css from mobile. Let me know if it looks good now.

**Comment by hn275** [comment]
noice. all is well

**Review by hn275 — APPROVED** [review]

**Pull request merged**
