### PR TITLE
Reduxjs

### PR DESCRIPTION
**Pull request by hn275**
The logic for new post is working, I'm going to how to attach comments into each post since Reddit's API separates comments and posts altogether :/

### CODE REVIEW

**Comment by Chuck-Gibson** [comment]
you're naming conventions are throwing me for a little loop, am i seeing 2 folders named allPosts? and an Index.js thats actually an AllPostsSlice?

**Comment by Chuck-Gibson** [comment]
should we also change the naming convention from "allPosts" to just "posts "? If we click on a subreddit we would just want it loading that subreddit's posts vs all posts

**Comment by hn275** [comment]
> you're naming conventions are throwing me for a little loop, am i seeing 2 folders named allPosts? and an Index.js thats actually an AllPostsSlice?

I'm.. only seeing one of that folder, maybe this is a github thing? or am i blind lol.



> should we also change the naming convention from "allPosts" to just "posts "? If we click on a subreddit we would just want it loading that subreddit's posts vs all posts

Oh yea you can change the name however you want, i just used `index.js` as force of habits because i usually structure my project a bit different. I used the name `allPosts` just so you are not confused with the actual post requests that I'm going to add later on once we tack on the login feature, if you just make the changes onto the main branch, I can fetch it later

**Comment by Chuck-Gibson** [comment]
>I'm.. only seeing one of that folder,

My bad github was displaying it weird and now i see its nested in Slices

>Oh yea you can change the name however you want, if you just make the changes onto the main branch, I can fetch it later

likely easier in the PR and just resubmit (ive never altered a PR yet as they've all been my own) otherwise i have to clone your branch and do a seperate PR or fix in main with the potential of missing a dependency  change somewhere

> I used the name allPosts just so you are not confused with the actual post requests that I'm going to add later on once we >tack on the login feature

Would we not just use userPosts, or selectedPost for more specific stuff later?

**Pull request closed without merging**
